openapi: '3.0.1'
info:
  version: '1.0.0'
  title: Checkout.com API Reference
  x-logo:
    url: 'https://assets.checkout.com/docs/logos/logo-checkout-api-dark.svg'
    altText: 'Checkout.com API logo'
  contact:
    name: Checkout.com Support
    url: 'https://checkout.com'
    email: support@checkout.com
  license:
    name: Checkout.com
    url: 'https://checkout.com/api/license/'
  termsOfService: 'https://checkout.com/terms/'
  description: >
    ## Get started

    Checkout.com provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard <a href="https://www.checkout.com/docs/resources/codes/http-response-codes">HTTP response codes</a>.

    You can consume the APIs directly using your favorite HTTP/REST library or make use of one of our <a href="https://www.checkout.com/docs/integrate/sdks" target="_blank">SDKs</a>.

    We have a testing environment called sandbox, which you can <a href="https://www.checkout.com/get-test-account">sign up for</a> to test API calls without affecting live data.

    ### Base URLs

    Use the following base URLs when making requests to the APIs:

      | Environment   |      Base URL                                        |
      |---------------|------------------------------------------------------|
      | Sandbox       |  https://api.sandbox.checkout.com/                   |
      | Production    |  https://api.checkout.com/                           |

    ### Looking for more guidance?

    Depending on what integration you need, we've provided <a href="https://www.checkout.com/docs/integrate/">guides to get you set up</a>.

    ###Â Not using APIs?

    We've partnered with many popular <a href="https://www.checkout.com/docs/integrate/e-commerce-platforms">e-commerce platforms</a> so you can get up and running quickly, processing online payments with one of our e-commerce plugins.

    # Authentication

    When you sign up for an account, you are given a secret and public API key
    pair. You authenticate with our API by providing the appropriate key in
    the request Authorization header.

    Never share your secret keys. Keep them guarded and secure.

    # Changelog

      | Date       | Description of change                                                |
      | ---------- | -------------------------------------------------------------------- |
      | 2022/01/26 | Update code samples for Java.                                        |
      | 2022/01/25 | Update code samples for C#.                                          |
      | 2022/01/13 | Update code samples for Node JS.                                     |
      | 2021/12/17 | Added `payment_type`, `payment_ip` and `billing_descriptor` to Hosted Payments and Payment Links Get endpoints. |
      | 2021/12/14    |  Removed upper limit for `products.price`                         |
      | 2021/11/19 | Added specification for "Get Hosted Payments Page details" endpoint. |
      | 2021/11/11 | Added `3ds.challenge_indicator` to card payment requests.            |
      | 2021/10/18 | Added `processing.purpose` to card payouts.                          |
      | 2021/10/18 | Added `recommendation_code` to payment response.                     |

servers:
  - url: https://api.checkout.com
    description: Live API
  - url: https://api.sandbox.checkout.com
    description: Sandbox API
tags:
  - name: Payments
    description: Process and manage payments from a variety of sources and to various destinations all within one integration.
  - name: Payment Links
    description: Create a Payment Link to accept and process payment details.
  - name: Hosted Payments Page
    description: Create a Hosted Payments Page to accept and process payment details.
  - name: Sources
    description: Create a payment source for a customer that you can use for one or more payments.
  - name: Tokens
    description: Create a token that represents a card's details (or their tokenized form in a digital wallet) that you can later use to request a payment, without you having to process or store any sensitive information.
  - name: Instruments
    description: Create a payment instrument that you can later use as the source or destination for one or more payments.
  - name: Webhooks
    description: Create and manage the webhook notifications you receive to keep up to date with the status of your transactions.
  - name: Events
    description: Use events to monitor and get insights into your transactions.
  - name: Disputes
    description: Keep track of and act on your open disputes (also known as chargebacks) to submit the best possible response.
  - name: Reconciliation
    description: Quickly find all fees associated with each of your payments, so you can concentrate on the important stuff while streamlining your financial reporting.
  - name: Risk
    description: Evaluate the risk of a transaction at the pre-authentication and pre-capture stages of the payment process.
  # - name: Files
  #   description: |
  #     Upload files to be used as input to other APIs
x-tagGroups:
  - name: Handle payments and payouts
    tags:
      - Payments
      - Payment Links
      - Hosted Payments Page
  - name: Stored payment details
    tags:
      - Tokens
      - Sources
      - Instruments
      - Customers
  - name: Notifications
    tags:
      - Events
      - Webhooks
  - name: Disputes
    tags:
      - Disputes
  - name: Risk management
    tags:
      - Risk
  - name: Statements and reporting
    tags:
      - Reconciliation
