type: object
description: Use the processing object to influence or override the data sent during card processing
properties:
  # mid:
  #   type: string
  #   description: Overrides the default merchant/acceptor identifier (MID) configured on your account
  #   example: "1234567"
  # senderInformation:
  #   type: object
  #   description: |
  #     Allows you to send additional data required for Visa Direct Original Credit Transaction (OCT) and Mastercard Moneysend payments.
  aft:
    type: boolean
    description: Indicates whether the payment is an [Account Funding Transaction](https://docs.checkout.com/four/payments/manage-payments/account-funding-transactions)
  preferred_scheme:
    type: Enum
    enum:
      - "mastercard"
      - "visa"
      - "cartes_bancaires"
    description: The preferred scheme for co-badged card payment processing. If using 3rd party Authentication before requesting the payment, set the value to the scheme that authenticated the transaction.
  # dlocal:
  #   type: object
  #   description: Processing information required for dLocal payments.
  #   properties:
  #     country:
  #       type: string
  #       description: The two-letter ISO code of the cardholder's country.
  #       example: "MX"
  #     payer:
  #       type: object
  #       description: Details about the cardholder.
  #       properties:
  #         document:
  #           type: string
  #           description: The cardholder's personal identification number. The identification required is country-specific. See the <a href="https://docs.dlocal.com/api-documentation/payins-api-reference/country-reference#documents" target="_blank">dLocal documentation</a> for more information.
  #           example: "DocumentId"
  #         name:
  #           type: string
  #           description: The cardholder's full name.
  #           example: "John Doe"
  #         email:
  #           type: string
  #           description: The cardholder's email address.
  #           example: "john.doe@example.com"
  #     installments:
  #       type: object
  #       description: Details about the installments.
  #       properties:
  #         count:
  #           type: string
  #           description: The number of payments to be made in the installment plan.
  #           example: "3"
  PayPal:
    type: object
    description: Processing information required for PayPal payments.
    properties:
      invoice_id:
        type: string
        description: Invoice id number
        maxLength: 127
      brand_name:
        type: string
        description: |
          The label that overrides the business name in the PayPal account
          on the PayPal pages
        maxLength: 127
        example: Super Brand
      locale:
        type: string
        pattern: "^[a-z]{2}(?:-[A-Z][a-z]{3})?(?:-(?:[A-Z]{2}))?$"
        description: ISO 639-2 language code
        example: en-US
        maxLength: 10
        minLength: 2
      shipping_preference:
        type: string
        description: Shipping preference
        enum:
          - NO_SHIPPING
          - SET_PROVIDED_ADDRESS
          - GET_FROM_FILE
        example: SET_PROVIDED_ADDRESS
      user_action:
        type: string
        description: Property required by PayPal to have an appropriate payment flow
        enum:
          - PAY_NOW
          - CONTINUE
        example: PAY_NOW
      set_transaction_context:
        type: object
        description: Set Transaction Context(Stc) data    
      supplementary_data:
        type: object
        properties:
          airline:
            type: array
            items:
              type: object
              required:
                - ticket
                - passenger
                - flight_leg_details
              properties:
                ticket:
                  type: object
                  properties:
                    number:
                      type: string
                      description: Ticket number/id as issued by the airline.
                      maxLength: 16
                      minLength: 1
                    issue_date:
                      type: string
                      pattern: "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$"
                      description: Date the airline ticket was issued.
                      maxLength: 10
                      minLength: 10
                    issuing_carrier_code:
                      type: string
                      pattern: "^[A-Z0-9]{2}$"
                      description: Carrier code of the ticket issuer.
                      maxLength: 2
                      minLength: 2
                    travel_agency_name:
                      type: string
                      description: Name of the travel agency that issued the ticket.
                      maxLength: 25
                      minLength: 1
                    travel_agency_code:
                      type: string
                      description: The IATA two-letter accounting code that identifies the carrier.
                      maxLength: 16
                      minLength: 1
                passenger:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: object
                      required:
                        - full_name
                      properties:
                        full_name:
                          type: string
                          description: When the party is a person, the party's full name.
                          maxLength: 300
                          minLength: 1
                    date_of_birth:
                      type: string
                      pattern: "^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$"
                      description: The date of birth of the passenger.
                      maxLength: 10
                      minLength: 10
                    country_code:
                      type: string
                      pattern: "^([A-Z]{2}|C2)$"
                      description: The passenger's country of residence.
                      maxLength: 2
                      minLength: 2
                flight_leg_details:
                  type: array
                  items:
                    type: object
                    required:
                      - departure_airport
                      - arrival_airport
                    properties:
                      flight_number:
                        type: number
                      carrier_code:
                        type: string
                      service_class:
                        type: string
                      departure_date:
                        type: string
                      departure_time:
                        type: string
                      departure_airport:
                        type: string
                      arrival_airport:
                        type: string
                      stopover_code:
                        type: string
                      fare_basis_code:
                        type: string
    
