type: object
description: Use the processing object to influence or override the data sent during card processing
properties:
  # mid:
  #   type: string
  #   description: Overrides the default merchant/acceptor identifier (MID) configured on your account
  #   example: "1234567"
  # senderInformation:
  #   type: object
  #   description: |
  #     Allows you to send additional data required for Visa Direct Original Credit Transaction (OCT) and Mastercard Moneysend payments.
  order_id:
    type: string
    description: The number provided by the cardholder. Purchase order or invoice number may be used.
    maxLength: 17
    example: '123456789'
  otp_value:
    type: string
    description: One time password sent to customer by SMS.
    maxLength: 50
    example: '966557877988'
  tax_amount:
    type: number
    description: Contains the customerâ€™s value-added tax registration number.
    minimum: 0
    example: 3000
  discount_amount:
    type: number
    description: The discount amount applied to the transaction by the merchant.
    minimum: 0
    example: 000
  duty_amount:
    type: number
    description: The total charges for any import/export duty included in the transaction.
    minimum: 0
    example: 000
  shipping_amount:
    type: number
    description: The total freight or shipping and handling charges for the transaction.
    minimum: 0
    example: 300
  shipping_tax_amount:
    type: number
    description: The tax amount of the freight or shipping and handling charges for the transaction.
    minimum: 0
    example: 100
  aft:
    type: boolean
    description: Indicates whether the payment is an [Account Funding Transaction](https://www.checkout.com/docs/payments/manage-payments/account-funding-transactions)
  preferred_scheme:
    type: Enum
    enum:
      - 'mastercard'
      - 'visa'
      - 'cartes_bancaires'
    description: The preferred scheme for co-badged card payment processing. If using 3rd party Authentication before requesting the payment, set the value to the scheme that authenticated the transaction.
  merchant_initiated_reason:
    type: string
    enum:
      - 'Delayed_charge'
      - 'Resubmission'
      - 'No_show'
      - 'Reauthorization'
    description: Indicates the reason for a merchant initiated payment request.
  campaign_id:
    type: integer
    description: "Unique number of the campaign this payment will be running in. Only required for Afterpay campaign invoices."
  # dlocal:
  #   type: object
  #   description: Processing information required for dLocal payments.
  #   properties:
  #     country:
  #       type: string
  #       description: The two-letter ISO code of the cardholder's country.
  #       example: "MX"
  #     payer:
  #       type: object
  #       description: Details about the cardholder.
  #       properties:
  #         document:
  #           type: string
  #           description: The cardholder's personal identification number. The identification required is country-specific. See the <a href="https://docs.dlocal.com/api-documentation/payins-api-reference/country-reference#documents" target="_blank">dLocal documentation</a> for more information.
  #           example: "DocumentId"
  #         name:
  #           type: string
  #           description: The cardholder's full name.
  #           example: "John Doe"
  #         email:
  #           type: string
  #           description: The cardholder's email address.
  #           example: "john.doe@example.com"
  #     installments:
  #       type: object
  #       description: Details about the installments.
  #       properties:
  #         count:
  #           type: string
  #           description: The number of payments to be made in the installment plan.
  #           example: "3"
  product_type:
    type: string
    required: true
    enum:
      - QR Code
      - In-App
      - Official Account
      - Mini Program
    description: Product type of the payment. Required if `source.type` is `wechatpay`
    example: QR Code
  open_id:
    type: string
    description: Value obtained from WeChat Web Authorization API before initiating Official Account or Mini Program payments. Required if `source.type` is `wechatpay` and `processing.product_type` is `Official Account` or `Mini Program`
    example: oUpF8uMuAJO_M2pxb1Q9zNjWeS6o
  original_order_amount:
    type: number
    minimum: 0
    description: The payment for a merchant's order may be split, and the original order price indicates the transaction amount of the entire order
    example: 10
  receipt_id:
    type: string
    maxLength: 32
    description: Merchant receipt ID
    example: 10
  terminal_type:
    enum:
      - APP
      - WAP
      - WEB
    type: string
    description: The client-side terminal type, if it is a website that is opened via a PC browser or a mobile browser or mobile application.
    default: WEB
    example: WAP
  os_type:
    enum:
      - ANDROID
      - IOS
    type: string
    description: This field is required when terminalType is not WEB.
    example: ANDROID
  invoice_id:
    type: string
    description: Invoice ID number
    maxLength: 127
  brand_name:
    type: string
    description: |
      The label that overrides the business name in the PayPal account
      on the PayPal pages
    maxLength: 127
    example: Super Brand
  locale:
    type: string
    pattern: '^[a-z]{2}(?:-[A-Z][a-z]{3})?(?:-(?:[A-Z]{2}))?$'
    description: ISO 639-2 language code
    example: en-US
    maxLength: 10
    minLength: 2
  shipping_preference:
    type: string
    description: Shipping preference
    enum:
      - NO_SHIPPING
      - SET_PROVIDED_ADDRESS
      - GET_FROM_FILE
    example: SET_PROVIDED_ADDRESS
  user_action:
    type: string
    description: Property required by PayPal to have an appropriate payment flow
    enum:
      - PAY_NOW
      - CONTINUE
    example: PAY_NOW
  set_transaction_context:
    type: object
    properties:
      key:
        type: string
        description: The key for the pair.
      value:
        type: string
        description: The value for the pair.
    description: An array of key-and-value pairs with merchant-specific data for the transaction.
  airline_data:
    type: array
    items:
      type: object
      required:
        - ticket
        - passenger
        - flight_leg_details
      properties:
        ticket:
          type: object
          properties:
            number:
              type: string
              description: Ticket number/ID as issued by the airline.
              maxLength: 16
              minLength: 1
            issue_date:
              type: string
              pattern: '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$'
              description: Date the airline ticket was issued.
              maxLength: 10
              minLength: 10
            issuing_carrier_code:
              type: string
              pattern: '^[A-Z0-9]{2}$'
              description: Carrier code of the ticket issuer.
              maxLength: 2
              minLength: 2
            travel_agency_name:
              type: string
              description: Name of the travel agency that issued the ticket.
              maxLength: 25
              minLength: 1
            travel_agency_code:
              type: string
              description: The IATA two-letter accounting code that identifies the carrier.
              maxLength: 16
              minLength: 1
        passenger:
          type: object
          required:
            - name
          properties:
            name:
              type: object
              required:
                - full_name
              properties:
                full_name:
                  type: string
                  description: When the party is a person, the party's full name.
                  maxLength: 300
                  minLength: 1
            date_of_birth:
              type: string
              pattern: '^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$'
              description: The date of birth of the passenger.
              maxLength: 10
              minLength: 10
            country_code:
              type: string
              pattern: '^([A-Z]{2}|C2)$'
              description: The passenger's country of residence.
              maxLength: 2
              minLength: 2
        flight_leg_details:
          type: array
          items:
            type: object
            required:
              - departure_airport
              - arrival_airport
            properties:
              flight_number:
                type: number
              carrier_code:
                type: string
              service_class:
                type: string
              departure_date:
                type: string
              departure_time:
                type: string
              departure_airport:
                type: string
              arrival_airport:
                type: string
              stopover_code:
                type: string
              fare_basis_code:
                type: string
