name: Node.js CI

on: [ pull_request ]

env:
  CI: true

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Install node modules
        run: npm ci --ignore-scripts

      - name: Build ABC & NAS specs
        run: npm run build:all

      - name: Validate schema
        run: |
          npm run test:abc
          npm run test:nas

      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: web_deploy

  check-broken-links:
    needs: run-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: web_deploy
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/link-checker/requirements.txt ]; then pip install -r scripts/link-checker/requirements.txt; fi
      - name: Check for broken links
        run: |
          python scripts/link-checker/link-checker.py